apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-app
  labels:
    app: wisecow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow-app
  template:
    metadata:
      labels:
        app: wisecow-app
    spec:
      containers:
        - name: wisecow-app  
          image: bhagwathudge/wisecow-app:latest
          ports:
            - containerPort: 4499
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          # Ensuring the container does not exit immediately
          command: ["/bin/bash", "-c", "/app/wisecow.sh"]
